services:
  devices-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro